### ISSUE TITLE
Function "Site" not defined 

### ISSUE THREAD

**Issue by asebold** [JugglerX/hugo-serif-theme#2]
Added theme to hugo site, ran hugo and got
`parse failed: template: team/summary.html:4: function "Site" not defined"`

In layouts/team/summary.html on line 4, a period is missing in front of "Site"

Plz change `{{Site.BaseURL}}` to `{{.Site.BaseURL}}`

Love the theme btw!

**Comment by JugglerX** [comment]
I have fixed that typo. Appreciate the bug report mate!
