### ISSUE TITLE
External html and JS content not loading?

### ISSUE THREAD

**Issue by Mr-Sheep** [JugglerX/hugo-serif-theme#21]
I been trapped by this for a long time, but when I tried to put html or JS code blocks into the markdown file Im writing. The code block doesn't show up in the html file generate by hugo
I was trying:
```
<script src='/path-to-your-javascript-file/pdfobject.js'></script>
<script>
PDFObject.embed("link-to-pdf");
</script>
```

**Comment by JugglerX** [comment]
Not sure you can include scripts in the markdown. Or if you do, you might need to render the {{ .Content }} with some kind of special filter. Hugo probably strips <script> tags for security reasons.

**Comment by Mr-Sheep** [comment]
I thought I could directly use html code blocks in markdown. Anyways, I’ll give it a try.
Thx
