### ISSUE TITLE
Mobile menu shows off-screen for wide pages

### ISSUE THREAD

**Issue by graynk** [JugglerX/hugo-serif-theme#22]
Hi. I have a page with a table that is fairly wide (so on mobiles there's a horizontal scrollbar).

It's pretty difficult to break this table apart, so it's going to take a lot of space anyway. However, the side effect of that is that menu appears centered based on that width. It's not a problem if I make browser window small on PC

![screen2small](https://user-images.githubusercontent.com/3626328/77069517-61212200-6a0a-11ea-8987-61729a459657.jpg)

But it shows up wrong on mobile. What can I do to fix this?

![screen1small](https://user-images.githubusercontent.com/3626328/77069508-5e263180-6a0a-11ea-9ca8-753ec2532131.jpg)

**Comment by graynk** [comment]
adding `position: fixed` to `.lock-scroll` sort of resolves this: menu appears correctly, but close button remains out of sight. It's not ideal, but bearable. If you have any tips on how to make close button show properly as well, I'd be glad to hear them.

**Comment by JugglerX** [comment]
You just need to fiddle with the CSS until you get it right. 

Maybe you could set the height and width of the mobile menu using `vh` and `vw` - this might stop it from expanding when the table is wider then the page.
