### ISSUE TITLE
Home title does not change title of the theme

### ISSUE THREAD

**Issue by sbsends** [JugglerX/hugo-serif-theme#23]
<img width="273" alt="Screen Shot 2020-04-18 at 1 40 57 PM" src="https://user-images.githubusercontent.com/21231577/79662683-44e3e280-817a-11ea-91e2-a1623794aa7f.png">
<img width="248" alt="Screen Shot 2020-04-18 at 1 40 52 PM" src="https://user-images.githubusercontent.com/21231577/79662688-457c7900-817a-11ea-90c7-cb5654fc0708.png">

Navigating to the `/` path results in the title being the full path

However, navigating to any other location correctly names the title.

How can I fix this?

**Comment by int02h** [comment]
You can set the title for `/` in `config.toml` that placed right in the root of your site. Add `title` field to the `[params]` section. Like the following:
```
[params]
  title="YOUR TITLE GOES HERE"
  google_analytics_id = ""
  google_tag_manager_id = ""
...
```
