### ISSUE TITLE
strong and em present in html source but not showing in rendered page

### ISSUE THREAD

**Issue by PavoDive** [JugglerX/hugo-serif-theme#28]
I'm using hugo-serif-theme together with Rmarkdown. I had to make some minor tweaks here and there, but overall it is working well.

I'm surprised though, as both italics and bolds aren't properly shown in the pages, even though they are there in the html source.

See the last two paragraphs in [this page](https://gpavolini.netlify.app/blog/ense%C3%B1anzas-de-la-pandemia-realmente-aprendimos-algo/):

**Html Source**:

`Puede ser afectada por eventos naturales o sociales <em>que ocurren en otros continentes</em>. `
and

`si usted y su empresa ejecutan <strong>hoy</strong> las acciones correctas`

But is showed as plain text in the rendered page.

I don't know if this is a feature or the result of me using Rmarkdown. If so, I'd appreciate your guidance on where to look and have the theme to render bolds and italics as desired.

Thanks!

**Comment by viasun** [comment]
Exactly the same issue with my site. No resolution yet.

**Comment by JugglerX** [comment]
Hi

You just need to add the following css to `assets/scss/components/_content.scss`

```
  strong {
    font-width: bold;
  }
  em {
    font-style: italic;
  }
```

Alternatively I have pushed an update for the theme which improves the typography of markdown content quite a bit.

**Comment by PavoDive** [comment]
This worked nicely. I guess that once you commit the changes to the theme this issue can be closed.

Thanks @JugglerX !!

> You just need to add the following css to `assets/scss/components/_content.scss`
> 
> ```
>   strong {
>     font-width: bold;
>   }
>   em {
>     font-style: italic;
>   }
> ```

**Comment by JugglerX** [comment]
The changes are commited, but they are not like above. The updates I pushed do fix em and strong but they also refactor a lot of other stuff. If you just want to fix this small issue I recommend just patching the content.scss with these changes yourself.
