### ISSUE TITLE
Floating bottom-right pixel width display?

### ISSUE THREAD

**Issue by austinj** [JugglerX/hugo-serif-theme#29]
For whatever reason, there's a floating display in the bottom-right of my pages that shows the current width of the window in pixels (see below for an example). Haven't been able to track it down; any clues as to where this might be living so I can remove it?

![Screen Shot 2020-07-06 at 3 58 30 PM](https://user-images.githubusercontent.com/1855202/86662448-92b1ff00-bfa1-11ea-8f50-4127cc5fd0e1.png)

**Comment by JugglerX** [comment]
@austinj This shows the current CSS Breakpoints. It only appears when running the dev server, not after `hugo` build.

If you wish to remove it completely you will find it in `style.scss` at the bottom.

**Comment by austinj** [comment]
Great, thank you!
