### ISSUE TITLE
Forked Repository No Longer Working

### ISSUE THREAD

**Issue by ChrisStayte** [JugglerX/hugo-serif-theme#3]
I forked this repository and altered the 'SCSS'. Now when I build the site on Netlify. I get 
```
8:24:56 PM: Building sites …
8:24:56 PM: ERROR 2018/12/21 01:24:56 error: failed to transform resource: TOCSS: failed to transform "scss/style.scss" (text/x-scss): this feature is not available in your current Hugo version
```

**Comment by JugglerX** [comment]
You need to make sure you commit the resources folder to git for it to
build on Netlify. They have a known issue related to this on Netlify.

**Comment by ChrisStayte** [comment]
I deleted the resources from the theme because it was not updating the CSS styling. How do I get the theme to regen the minified css?

**Comment by JugglerX** [comment]
When you do a Hugo build it should generate the resources folder in the
root. Make sure this folder isn't git ignored. Normally you should not
commit this folder but in the case of Netlify for the time being you need
too

**Comment by ChrisStayte** [comment]
I tried that. It's not taking the changes I made to the CSS. If you wouldn't mind to take a look I would appreciate it :) https://github.com/ChrisStayte/BubbleBrush

**Comment by ChrisStayte** [comment]
I got it. Thanks you
