### ISSUE TITLE
Hamburger close button disappears in website resize

### ISSUE THREAD

**Issue by NicoHood** [JugglerX/hugo-serif-theme#31]
Small edge case bug:

If you open the theme in a very small footprint (mobile view), open the hamburger menu, then resize the page, the close button (X) will disappear.

**Comment by JugglerX** [comment]
I cannot reproduce this.

I used chrome dev tools in responsive view across various sizes and the menu didn't disappear.

Is this a real use case? 
If the user was actually on a mobile device, they coulden't resize their screen?

**Comment by NicoHood** [comment]
This happened while testing on my pc with firefox. As I said, this is a small edga case, but for me this is reproducible.

**Comment by JugglerX** [comment]
@NicoHood thank you for the bug report. I'll keep an eye out for it while testing in the future.
