### ISSUE TITLE
stackbit issue

### ISSUE THREAD

**Issue by stephenajulu** [JugglerX/hugo-serif-theme#32]
Loading site /tmp/909d8133-b79c-4a9c-8e88-07760ab1d1e0
Error loading theme at /tmp/909d8133-b79c-4a9c-8e88-07760ab1d1e0

To get this error, click the 'Create with Stackbit' button.
Fails during validation with those 2 errors.

Great theme though. Especially the new look.

**Comment by JugglerX** [comment]
Thanks for the report, I definitely want to keep supporting Stackbit so I will get a fix fo this as soon as I can. I'll let you know once I'm done.

**Comment by JugglerX** [comment]
should be a few more days before this is fixed

**Comment by JugglerX** [comment]
@stephenajulu should be working now
