### ISSUE TITLE
Footer out of place in IE 11

### ISSUE THREAD

**Issue by florianbeisel** [JugglerX/hugo-serif-theme#4]
When viewing the theme in Microsoft Internet Explorer, the footer and subfooter are not displayed at the bottom of the page but at the top. This is due to the way IE interprets the shorthand `flex: 1;`.

A possible fix is to set the attribute to `flex: 1 0 0;` in `assets\scss\components\_page.scss`

Sorry for not fixing this right away and submitting a PR, but I'm bad at git. :smile: 

As an aside, this is a beautiful theme and I want to thank you for the work you put in it.

**Comment by JugglerX** [comment]
Thanks for reporting it. I'll fix it up. Don't worry about the PR, at least you made an issue!

**Comment by JugglerX** [comment]
i updated the scss file with your proposed fix. I assume it's working, but I don't have ie11 to test with.
