### ISSUE TITLE
Changing the title from "hugoserif" to custom title and changing homepage background image

### ISSUE THREAD

**Issue by chriscastille6** [JugglerX/hugo-serif-theme#6]
I've tried to figure out how to change the title from "hugoserif" to a custom title. No dice. Could you please clarify?

Also, how would I go about changing the homepage background image?

**Comment by JugglerX** [comment]
Which title are you talking about? 
The themes title is "Hugo Serif Theme" defined in config.toml.
There is also a meta title for the homepage declared in `layouts/index.html`

**Comment by chriscastille6** [comment]
In the upper left-hand of the webpage, the word "hugoserif" is printed. I've modified the config.toml but that hasn't worked. 

Also – what of my second question? How would I change the background image?

**Comment by JugglerX** [comment]
The title in the top left is the logo. So you need to replace the logo image in the `static/images/logo.svg` with you own logo.

The latest version allows you to specify your logo directly in the `config.toml`

The background image was controlled via CSS. In the latest version you can specify the intro image in the markdown file. So for example in `content/index.md` change the front matter property `intro_image` to the path where your image is located (likely in `static/images/` folder.
